Make this library compatible with 3.8+
Tinche/tightwrap pull request #1
Opened 2024-04-29 14:53 UTC by InSyncWithFoo

Since the main use of this library seems to be type checking, I think it's a good thing to make this library also usable in 3.8 and 3.9.

2024-04-29 14:56 UTC, Tinche requested changes

2024-04-29 14:56 UTC, Tinche commented on pyproject.toml
> +dependencies = [
Can you make this a conditional dependency? 3.8 and 3.9 only.

2024-04-29 15:53 UTC, InSyncWithFoo commented on pyproject.toml
> +dependencies = [
Done.

2024-04-30 14:21 UTC, Tinche commented
The tests are failing because `signature` doesn't allow `eval_str` on older Pythons. I guess that needs to be handled, and those versions can't support `from __future__ import annotations` properly I think.

2024-04-30 15:59 UTC, InSyncWithFoo commented
That could potentially be replaced with [`typing.get_type_hints()`](https://docs.python.org/3/library/typing.html#typing.get_type_hints) <s>(or, to be precise, [`typing_extensions.get_type_hints()`](https://github.com/python/typing_extensions/blob/c79c561ec62a09e5a62d14c12ccae4d7cb273da0/src/typing_extensions.py#L1124))</s>. According to [this CPython issue](https://github.com/python/cpython/issues/82104), there are subtle differences, but I think it's good enough. Should I proceed?

2024-04-30 22:15 UTC, Tinche commented
Sure, give it a try!

2024-05-01 19:15 UTC, InSyncWithFoo commented
That was actually more complex than I thought. Anyway, tests pass now.

2024-05-04 12:40 UTC, Tinche commented
Thanks!

2024-05-04 12:40 UTC, merged